services:
  - type: web
    name: chat
    env: python
    plan: free
    region: frankfurt
    repo: https://github.com/xbeat/chat
    branch: main
    autoDeploy: true    
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ENV
        sync: false