services:
  - type: web
    name: chat
    env: python
    plan: free
    region: frankfurt
    repo: https://github.com/xbeat/chat
    branch: master
    autoDeploy: true    
    buildCommand: pip install -r requirements.txt
    startCommand: python chat.py
    envVars:
      - key: ENV
        value: prod